export default {
  colors: {
    black: "black",
    white: "white",
    danger: "#DC1637",
    info: "#12C2E9",
    warning: "#FFE900",
    success: "#2ec64e",
    background: "rgba(238, 238, 238, .2)",
    primary: "#142995",
    secondary: "#12C2E9",
    tertiary: "#A5FF32",
    backgroundDisabled: "#EEEEEE",
    textDisabled: "#BBBBBB",
  },

  fonts: {
    family: {
      regular: "PTSans-Regular",
      italic: "PTSans-Italic",
      boldItalic: "PTSans-BoldItalic",
      bold: "PTSans-Bold",
    },
    weight: {
      normal: "normal",
      bold: "bold",
      l1: "100",
      l2: "200",
      l3: "300",
      l4: "400",
      l5: "500",
      l6: "600",
      l7: "700",
      l8: "800",
      l9: "900",
      undefined,
    },
  },
  fontSize: {
    xxxs: `${1}px`,
    xxs: `${2}px`,
    xs: `${4}px`,
    small: `${8}px`,
    default: `${16}px`,
    medium: `${24}px`,
    large: `${32}px`,
    large2: `${36}px`,
    large3: `${40}px`,
    xLarge: `${44}px`,
    xxLarge: `${48}px`,
    xxxLarge: `${60}px`,
    veryLarge: `${76}px`,
    titlePage: `${20}px`,
    title: `${28}px`,
    specific: `${18}px`,
  },
  fontSizeNumber: {
    xxxs: 1,
    xxs: 2,
    xs: 4,
    small: 8,
    default: 16,
    medium: 24,
    large: 32,
    xLarge: 44,
    xxLarge: 48,
    xxxLarge: 60,
    veryLarge: 76,
    titlePage: 20,
    title: 28,
    specific: 18,
  },
  radius: {
    xxs: `${2}px`,
    xs: `${4}px`,
    small: `${8}px`,
    small2: `${12}px`,
    default: `${16}px`,
    medium: `${20}px`,
    medium2: `${24}px`,
    medium3: `${28}px`,
    large: `${32}px`,
    large2: `${36}px`,
    large3: `${40}px`,
    xLarge: `${44}px`,
    xxLarge: `${48}px`,
    xxxLarge: `${54}px`,
    veryLarge: `${76}px`,
  },
  radiusNumber: {
    xxs: 2,
    xs: 4,
    small: 8,
    small2: 12,
    default: 16,
    medium: 24,
    large: 32,
    large2: 36,
    large3: 40,
    xLarge: 44,
    xxLarge: 48,
    xxxLarge: 60,
    veryLarge: 76,
  },
  spaces: {
    xxs: `${2}px`,
    xs: `${4}px`,
    small: `${8}px`,
    default: `${16}px`,
    medium: `${20}px`,
    medium2: `${24}px`,
    medium3: `${28}px`,
    large: `${32}px`,
    large2: `${36}px`,
    large3: `${40}px`,
    xLarge: `${44}px`,
    xxLarge: `${48}px`,
    xxxLarge: `${54}px`,
    veryLarge: `${76}px`,
  },
  spacesNumber: {
    xxs: 2,
    xs: 4,
    small: 8,
    default: 16,
    medium: 24,
    large: 32,
    large2: 36,
    large3: 40,
    xLarge: 44,
    xxLarge: 48,
    xxxLarge: 60,
    veryLarge: 76,
  },
}
